"""Added upvotes and downvotes

Revision ID: 7e30f12eb912
Revises: efc042910b71
Create Date: 2025-05-07 19:19:49.118080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e30f12eb912'
down_revision: Union[str, None] = 'efc042910b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('upvotes', sa.Integer(), nullable=False))
    op.add_column('answers', sa.Column('downvotes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'downvotes')
    op.drop_column('answers', 'upvotes')
    # ### end Alembic commands ###
