"""initial schema

Revision ID: efc042910b71
Revises:
Create Date: 2025-05-06 19:04:51.023183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "efc042910b71"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "answers", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "idx_answer_search_vector",
        "answers",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "badges",
        "icon",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.add_column("categories", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("questions", sa.Column("view_count", sa.Integer(), nullable=False))
    op.add_column(
        "questions", sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True)
    )
    op.drop_index(
        "idx_questions_body_trgm", table_name="questions", postgresql_using="gin"
    )
    op.drop_index(
        "idx_questions_title_trgm", table_name="questions", postgresql_using="gin"
    )
    op.create_index(
        "idx_question_search_vector",
        "questions",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_question_search_vector", table_name="questions", postgresql_using="gin"
    )
    op.create_index(
        "idx_questions_title_trgm",
        "questions",
        ["title"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_questions_body_trgm",
        "questions",
        ["body"],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_column("questions", "search_vector")
    op.drop_column("questions", "view_count")
    op.drop_column("categories", "description")
    op.alter_column(
        "badges",
        "icon",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(
        "idx_answer_search_vector", table_name="answers", postgresql_using="gin"
    )
    op.drop_column("answers", "search_vector")
    # ### end Alembic commands ###
